### ISSUE TITLE
What does "class:size" do?

### ISSUE THREAD

**Issue by sirugh** [rsdavis/svelte-drawer#2]
https://github.com/rsdavis/svelte-drawer/blob/7d75f657d4186246ce893bc7974038cfdd7b03eb/src/Drawer.svelte#L40

It's unclear to me what this line does - I was curious if it was leftover.

**Comment by rsdavis** [comment]
It applies the class passed in from the user, if there is one. It sets the size of the drawer, in case you don't want it to cover the full width. You can see it in action in the demo https://svelte.dev/repl/32443b9fad6447fe899a60596537db31?version=3.24.1

**Comment by sirugh** [comment]
Hm - I was fairly sure that removing `class:size` didn't change anything - I was still able to modify drawer size via the prop.
