### ISSUE TITLE
DrawerProps Type doesn't allow top or bottom placement

### ISSUE THREAD

**Issue by disbelief** [rsdavis/svelte-drawer#4]
When using Typescript, the Drawer's `DrawerProps` type only permits `"left"` and `"right"` values for `placement`, which causes compile errors when trying to use it as a top or bottom drawer.

https://github.com/rsdavis/svelte-drawer/blob/de4900ae22a8173434a7d97f88808c712dc4d914/types/Drawer.svelte.d.ts#L15

**Comment by rsdavis** [comment]
@aabounegm Can you confirm?

**Comment by aabounegm** [comment]
Yes, that's indeed the case. I apologize for not noticing those 2 other values as I only used the docs and the demo as a reference.
The fix is really simple, I can submit a quick PR now.

**Comment by rsdavis** [comment]
Just published npm package v1.2.1 with the fix 

@disbelief Thanks for reporting
@aabounegm Thanks for the quick fix

**Comment by disbelief** [comment]
Awesome, thanks for the quick fix.
